import Foundation
import SwiftUI

// MARK: - Languages

enum FFLanguage: String, CaseIterable, Identifiable {
    static let storageKey = "ffLanguage"

    case english    = "en"
    case indonesian = "id"
    case vietnamese = "vi"
    case portuguese = "pt-BR"
    case moroccan   = "ar-MA"
    case arabic     = "ar"
    case taiwanese  = "zh-TW"

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .english:    return "English"
        case .indonesian: return "Indonesia"
        case .vietnamese: return "Tiếng Việt"
        case .portuguese: return "Português (BR)"
        case .moroccan:   return "Darija (المغرب)"
        case .arabic:     return "العربية"
        case .taiwanese:  return "繁體中文"
        }
    }

    var flagEmoji: String {
        switch self {
        case .english:    return "🇺🇸"
        case .indonesian: return "🇮🇩"
        case .vietnamese: return "🇻🇳"
        case .portuguese: return "🇧🇷"
        case .moroccan:   return "🇲🇦"
        case .arabic:     return "🇸🇦"
        case .taiwanese:  return "🇹🇼"
        }
    }

    var isRTL: Bool {
        self == .arabic || self == .moroccan
    }

    func t(_ key: String) -> String {
        strings[key] ?? key
    }

    // MARK: - Strings

    private var strings: [String: String] {
        switch self {

        // ─────────────────────────────────────── ENGLISH ─────────────────────
        case .english: return [
            // Navigation / Auth
            "select_language":        "Select Language",
            "continue":               "Continue",
            "login_title":            "FF External",
            "login_subtitle":         "Enter your license key to continue",
            "key_placeholder":        "FFEX-XXXX-XXXX-XXXX",
            "validate":               "Validate",
            "validating":             "Validating…",
            "key_invalid":            "Invalid or expired key",
            "key_valid":              "Access granted",
            "logout":                 "Logout",
            "logout_confirm_title":   "Logout",
            "logout_confirm_msg":     "You will need to enter your key again.",
            "logout_confirm_yes":     "Logout",
            "logout_confirm_cancel":  "Cancel",
            // License card
            "device":                 "Device",
            "expires":                "Expires",
            "key_label":              "License Key",
            "card_iphone":            "iPhone",
            "card_ios":               "iOS",
            "card_expires":           "Expires In",
            // Tabs
            "tab_ff":                 "Free Fire",
            "tab_ffmax":              "FF Max",
            // Inject
            "inject":                 "Inject Cheat",
            "restore":                "Restore Default",
            "injecting":              "Injecting…",
            "inject_success":         "Inject Success",
            "restore_success":        "Files Restored",
            "already_injected":       "Already Injected",
            "unavailable":            "Unavailable",
            "loading_files":          "Fetching cheat files…",
            // Telegram
            "telegram":               "Join Telegram for Updates",
            // Feature sections
            "section_aiming":         "Aiming",
            "section_movement":       "Movement",
            "section_combat":         "Combat",
            "section_esp":            "ESP",
            "section_hud":            "HUD",
            "section_stealth":        "Stealth",
            // Feature names
            "feat_aimsilent":         "AimSilent",
            "feat_aimsilent_sub":     "Bullets track enemy silently",
            "feat_aimbot":            "Aimbot",
            "feat_aimbot_sub":        "Auto-aim to target",
            "feat_fov":               "FOV Circle",
            "feat_fov_sub":           "Aim radius indicator",
            "feat_speed":             "Speed Hack",
            "feat_speed_sub":         "5× movement speed",
            "feat_bulletspeed":       "Bullet Speed",
            "feat_bulletspeed_sub":   "Fast fire rate",
            "feat_fps":               "FPS Unlock",
            "feat_fps_sub":           "144 FPS",
            "feat_esp_box":           "Box ESP",
            "feat_esp_box_sub":       "Enemy bounding box",
            "feat_esp_line":          "Line ESP",
            "feat_esp_line_sub":      "Line from screen edge to enemy",
            "feat_esp_health":        "Health Bar",
            "feat_esp_health_sub":    "Show enemy health",
            "feat_esp_name":          "Name Tag",
            "feat_esp_name_sub":      "Show enemy name",
            "feat_esp_distance":      "Distance Tag",
            "feat_esp_distance_sub":  "Show range in metres",
            "feat_esp_skeleton":      "Skeleton ESP",
            "feat_esp_skeleton_sub":  "Bone-line overlay",
            "feat_counter":           "Enemy Counter",
            "feat_counter_sub":       "Live count shown at screen top",
            "feat_streamproof":       "Streamproof",
            "feat_streamproof_sub":   "Hide ESP from recordings",
            // Sliders
            "slider_fov_radius":      "Radius",
            "slider_strength":        "Strength",
            "slider_distance":        "Max Distance",
            "lbl_metres":             "m",
            // Aimbot targets
            "target_head":            "Head",
            "target_neck":            "Neck",
            "target_body":            "Body",
            // Errors
            "err_device_mismatch":    "Key is bound to another device",
            "err_expired":            "License key has expired",
        ]

        // ──────────────────────────────────────── INDONESIA ──────────────────
        case .indonesian: return [
            "select_language":        "Pilih Bahasa",
            "continue":               "Lanjutkan",
            "login_title":            "FF External",
            "login_subtitle":         "Masukkan kunci lisensi untuk melanjutkan",
            "key_placeholder":        "FFEX-XXXX-XXXX-XXXX",
            "validate":               "Validasi",
            "validating":             "Memvalidasi…",
            "key_invalid":            "Kunci tidak valid atau kedaluwarsa",
            "key_valid":              "Akses diberikan",
            "logout":                 "Keluar",
            "logout_confirm_title":   "Keluar",
            "logout_confirm_msg":     "Kamu perlu masukkan key lagi nanti.",
            "logout_confirm_yes":     "Keluar",
            "logout_confirm_cancel":  "Batal",
            "device":                 "Perangkat",
            "expires":                "Kedaluwarsa",
            "key_label":              "Kunci Lisensi",
            "card_iphone":            "iPhone",
            "card_ios":               "iOS",
            "card_expires":           "Sisa Waktu",
            "tab_ff":                 "Free Fire",
            "tab_ffmax":              "FF Max",
            "inject":                 "Inject Cheat",
            "restore":                "Pulihkan Default",
            "injecting":              "Menginjeksi…",
            "inject_success":         "Inject Berhasil",
            "restore_success":        "File Dipulihkan",
            "already_injected":       "Sudah Diinjeksi",
            "unavailable":            "Tidak Tersedia",
            "loading_files":          "Mengambil file cheat…",
            "telegram":               "Bergabung Telegram untuk Update",
            "section_aiming":         "Membidik",
            "section_movement":       "Pergerakan",
            "section_combat":         "Tempur",
            "section_esp":            "ESP",
            "section_hud":            "HUD",
            "section_stealth":        "Stealth",
            "feat_aimsilent":         "AimSilent",
            "feat_aimsilent_sub":     "Peluru mengincar musuh secara diam-diam",
            "feat_aimbot":            "Aimbot",
            "feat_aimbot_sub":        "Auto-aim ke target",
            "feat_fov":               "Lingkaran FOV",
            "feat_fov_sub":           "Indikator radius bidik",
            "feat_speed":             "Speed Hack",
            "feat_speed_sub":         "Kecepatan gerak 5×",
            "feat_bulletspeed":       "Kecepatan Peluru",
            "feat_bulletspeed_sub":   "Rate of fire cepat",
            "feat_fps":               "Buka FPS",
            "feat_fps_sub":           "144 FPS",
            "feat_esp_box":           "Box ESP",
            "feat_esp_box_sub":       "Kotak pembatas musuh",
            "feat_esp_line":          "Line ESP",
            "feat_esp_line_sub":      "Garis dari tepi layar ke musuh",
            "feat_esp_health":        "Bar Darah",
            "feat_esp_health_sub":    "Tampilkan darah musuh",
            "feat_esp_name":          "Tag Nama",
            "feat_esp_name_sub":      "Tampilkan nama musuh",
            "feat_esp_distance":      "Tag Jarak",
            "feat_esp_distance_sub":  "Tampilkan jarak dalam meter",
            "feat_esp_skeleton":      "Skeleton ESP",
            "feat_esp_skeleton_sub":  "Overlay garis tulang",
            "feat_counter":           "Penghitung Musuh",
            "feat_counter_sub":       "Jumlah musuh di bagian atas layar",
            "feat_streamproof":       "Streamproof",
            "feat_streamproof_sub":   "Sembunyikan ESP dari rekaman",
            "slider_fov_radius":      "Radius",
            "slider_strength":        "Kekuatan",
            "slider_distance":        "Jarak Maksimum",
            "lbl_metres":             "m",
            "target_head":            "Kepala",
            "target_neck":            "Leher",
            "target_body":            "Badan",
            "err_device_mismatch":    "Key sudah terikat ke perangkat lain",
            "err_expired":            "Key lisensi sudah kedaluwarsa",
        ]

        // ──────────────────────────────────────── VIETNAMESE ─────────────────
        case .vietnamese: return [
            "select_language":        "Chọn Ngôn Ngữ",
            "continue":               "Tiếp Tục",
            "login_title":            "FF External",
            "login_subtitle":         "Nhập khóa bản quyền để tiếp tục",
            "key_placeholder":        "FFEX-XXXX-XXXX-XXXX",
            "validate":               "Xác Nhận",
            "validating":             "Đang xác nhận…",
            "key_invalid":            "Khóa không hợp lệ hoặc đã hết hạn",
            "key_valid":              "Truy cập được cấp",
            "logout":                 "Đăng Xuất",
            "logout_confirm_title":   "Đăng Xuất",
            "logout_confirm_msg":     "Bạn sẽ cần nhập lại khóa.",
            "logout_confirm_yes":     "Đăng Xuất",
            "logout_confirm_cancel":  "Hủy",
            "device":                 "Thiết bị",
            "expires":                "Hết hạn",
            "key_label":              "Khóa Bản Quyền",
            "card_iphone":            "iPhone",
            "card_ios":               "iOS",
            "card_expires":           "Còn Lại",
            "tab_ff":                 "Free Fire",
            "tab_ffmax":              "FF Max",
            "inject":                 "Chèn Cheat",
            "restore":                "Khôi Phục Mặc Định",
            "injecting":              "Đang chèn…",
            "inject_success":         "Chèn Thành Công",
            "restore_success":        "Đã Khôi Phục Tệp",
            "already_injected":       "Đã Chèn Rồi",
            "unavailable":            "Không Có Sẵn",
            "loading_files":          "Đang tải file cheat…",
            "telegram":               "Tham gia Telegram để cập nhật",
            "section_aiming":         "Nhắm Bắn",
            "section_movement":       "Di Chuyển",
            "section_combat":         "Chiến Đấu",
            "section_esp":            "ESP",
            "section_hud":            "HUD",
            "section_stealth":        "Ẩn Thân",
            "feat_aimsilent":         "AimSilent",
            "feat_aimsilent_sub":     "Đạn bám mục tiêu âm thầm",
            "feat_aimbot":            "Aimbot",
            "feat_aimbot_sub":        "Tự động nhắm mục tiêu",
            "feat_fov":               "Vòng FOV",
            "feat_fov_sub":           "Chỉ báo bán kính nhắm",
            "feat_speed":             "Speed Hack",
            "feat_speed_sub":         "Tốc độ di chuyển 5×",
            "feat_bulletspeed":       "Tốc Độ Đạn",
            "feat_bulletspeed_sub":   "Tốc độ bắn nhanh",
            "feat_fps":               "Mở Khóa FPS",
            "feat_fps_sub":           "144 FPS",
            "feat_esp_box":           "Box ESP",
            "feat_esp_box_sub":       "Hộp giới hạn kẻ địch",
            "feat_esp_line":          "Line ESP",
            "feat_esp_line_sub":      "Đường từ mép màn hình đến kẻ địch",
            "feat_esp_health":        "Thanh Máu",
            "feat_esp_health_sub":    "Hiển thị máu kẻ địch",
            "feat_esp_name":          "Tên Kẻ Địch",
            "feat_esp_name_sub":      "Hiển thị tên kẻ địch",
            "feat_esp_distance":      "Tag Khoảng Cách",
            "feat_esp_distance_sub":  "Hiển thị khoảng cách tính bằng mét",
            "feat_esp_skeleton":      "Skeleton ESP",
            "feat_esp_skeleton_sub":  "Overlay đường xương",
            "feat_counter":           "Đếm Kẻ Địch",
            "feat_counter_sub":       "Số kẻ địch ở đầu màn hình",
            "feat_streamproof":       "Streamproof",
            "feat_streamproof_sub":   "Ẩn ESP khỏi bản ghi",
            "slider_fov_radius":      "Bán Kính",
            "slider_strength":        "Cường Độ",
            "slider_distance":        "Khoảng Cách Tối Đa",
            "lbl_metres":             "m",
            "target_head":            "Đầu",
            "target_neck":            "Cổ",
            "target_body":            "Thân",
            "err_device_mismatch":    "Khóa đã được gắn với thiết bị khác",
            "err_expired":            "Khóa bản quyền đã hết hạn",
        ]

        // ──────────────────────────────────────── PORTUGUESE ─────────────────
        case .portuguese: return [
            "select_language":        "Selecionar Idioma",
            "continue":               "Continuar",
            "login_title":            "FF External",
            "login_subtitle":         "Digite sua chave de licença para continuar",
            "key_placeholder":        "FFEX-XXXX-XXXX-XXXX",
            "validate":               "Validar",
            "validating":             "Validando…",
            "key_invalid":            "Chave inválida ou expirada",
            "key_valid":              "Acesso concedido",
            "logout":                 "Sair",
            "logout_confirm_title":   "Sair",
            "logout_confirm_msg":     "Você precisará inserir sua chave novamente.",
            "logout_confirm_yes":     "Sair",
            "logout_confirm_cancel":  "Cancelar",
            "device":                 "Dispositivo",
            "expires":                "Expira em",
            "key_label":              "Chave de Licença",
            "card_iphone":            "iPhone",
            "card_ios":               "iOS",
            "card_expires":           "Expira em",
            "tab_ff":                 "Free Fire",
            "tab_ffmax":              "FF Max",
            "inject":                 "Injetar Cheat",
            "restore":                "Restaurar Padrão",
            "injecting":              "Injetando…",
            "inject_success":         "Injeção Concluída",
            "restore_success":        "Arquivos Restaurados",
            "already_injected":       "Já Injetado",
            "unavailable":            "Indisponível",
            "loading_files":          "Buscando arquivos de cheat…",
            "telegram":               "Entre no Telegram para Atualizações",
            "section_aiming":         "Mira",
            "section_movement":       "Movimento",
            "section_combat":         "Combate",
            "section_esp":            "ESP",
            "section_hud":            "HUD",
            "section_stealth":        "Furtividade",
            "feat_aimsilent":         "AimSilent",
            "feat_aimsilent_sub":     "Projéteis rastreiam inimigos silenciosamente",
            "feat_aimbot":            "Aimbot",
            "feat_aimbot_sub":        "Mira automática no alvo",
            "feat_fov":               "Círculo de FOV",
            "feat_fov_sub":           "Indicador de raio de mira",
            "feat_speed":             "Speed Hack",
            "feat_speed_sub":         "Velocidade de movimento 5×",
            "feat_bulletspeed":       "Velocidade da Bala",
            "feat_bulletspeed_sub":   "Cadência de tiro rápida",
            "feat_fps":               "Desbloq. FPS",
            "feat_fps_sub":           "144 FPS",
            "feat_esp_box":           "Box ESP",
            "feat_esp_box_sub":       "Caixa delimitadora do inimigo",
            "feat_esp_line":          "Line ESP",
            "feat_esp_line_sub":      "Linha da borda para o inimigo",
            "feat_esp_health":        "Barra de Vida",
            "feat_esp_health_sub":    "Exibir vida do inimigo",
            "feat_esp_name":          "Tag de Nome",
            "feat_esp_name_sub":      "Exibir nome do inimigo",
            "feat_esp_distance":      "Tag de Distância",
            "feat_esp_distance_sub":  "Distância em metros",
            "feat_esp_skeleton":      "Skeleton ESP",
            "feat_esp_skeleton_sub":  "Overlay de esqueleto",
            "feat_counter":           "Contador de Inimigos",
            "feat_counter_sub":       "Contagem exibida no topo da tela",
            "feat_streamproof":       "Streamproof",
            "feat_streamproof_sub":   "Ocultar ESP de gravações",
            "slider_fov_radius":      "Raio",
            "slider_strength":        "Intensidade",
            "slider_distance":        "Distância Máxima",
            "lbl_metres":             "m",
            "target_head":            "Cabeça",
            "target_neck":            "Pescoço",
            "target_body":            "Corpo",
            "err_device_mismatch":    "Chave vinculada a outro dispositivo",
            "err_expired":            "Chave de licença expirada",
        ]

        // ──────────────────────────────────────── MOROCCAN ARABIC ────────────
        case .moroccan: return [
            "select_language":        "اختار اللغة",
            "continue":               "كمّل",
            "login_title":            "FF External",
            "login_subtitle":         "دخل مفتاح الترخيص ديالك باش تكمّل",
            "key_placeholder":        "FFEX-XXXX-XXXX-XXXX",
            "validate":               "تحقق",
            "validating":             "كيتحقق…",
            "key_invalid":            "المفتاح ماصحيحش أو منتهي",
            "key_valid":              "الوصول مسموح",
            "logout":                 "خروج",
            "logout_confirm_title":   "خروج",
            "logout_confirm_msg":     "غادي تحتاج تدخل المفتاح ديالك مرة أخرى.",
            "logout_confirm_yes":     "خروج",
            "logout_confirm_cancel":  "إلغاء",
            "device":                 "الجهاز",
            "expires":                "ينتهي",
            "key_label":              "مفتاح الترخيص",
            "card_iphone":            "آيفون",
            "card_ios":               "iOS",
            "card_expires":           "الوقت الباقي",
            "tab_ff":                 "فري فاير",
            "tab_ffmax":              "FF Max",
            "inject":                 "حقن الشيت",
            "restore":                "ارجع للأصل",
            "injecting":              "كيحقن…",
            "inject_success":         "الحقن نجح",
            "restore_success":        "الملفات رجعت",
            "already_injected":       "تم الحقن بالفعل",
            "unavailable":            "ماكاينش",
            "loading_files":          "كيجيب ملفات الشيت…",
            "telegram":               "انضم لتيليغرام للتحديثات",
            "section_aiming":         "التصويب",
            "section_movement":       "الحركة",
            "section_combat":         "القتال",
            "section_esp":            "ESP",
            "section_hud":            "HUD",
            "section_stealth":        "الإخفاء",
            "feat_aimsilent":         "AimSilent",
            "feat_aimsilent_sub":     "الرصاص يتبع العدو بصمت",
            "feat_aimbot":            "Aimbot",
            "feat_aimbot_sub":        "تصويب تلقائي على الهدف",
            "feat_fov":               "دائرة FOV",
            "feat_fov_sub":           "مؤشر نطاق التصويب",
            "feat_speed":             "Speed Hack",
            "feat_speed_sub":         "سرعة حركة 5×",
            "feat_bulletspeed":       "سرعة الرصاص",
            "feat_bulletspeed_sub":   "معدل رمي سريع",
            "feat_fps":               "فتح FPS",
            "feat_fps_sub":           "144 FPS",
            "feat_esp_box":           "Box ESP",
            "feat_esp_box_sub":       "صندوق حدود العدو",
            "feat_esp_line":          "Line ESP",
            "feat_esp_line_sub":      "خط من حافة الشاشة للعدو",
            "feat_esp_health":        "شريط الصحة",
            "feat_esp_health_sub":    "عرض صحة العدو",
            "feat_esp_name":          "اسم العدو",
            "feat_esp_name_sub":      "عرض اسم العدو",
            "feat_esp_distance":      "المسافة",
            "feat_esp_distance_sub":  "المسافة بالأمتار",
            "feat_esp_skeleton":      "Skeleton ESP",
            "feat_esp_skeleton_sub":  "طبقة هيكل العظمي",
            "feat_counter":           "عداد الأعداء",
            "feat_counter_sub":       "عدد الأعداء فوق الشاشة",
            "feat_streamproof":       "Streamproof",
            "feat_streamproof_sub":   "إخفاء ESP من التسجيل",
            "slider_fov_radius":      "النطاق",
            "slider_strength":        "القوة",
            "slider_distance":        "أقصى مسافة",
            "lbl_metres":             "م",
            "target_head":            "الرأس",
            "target_neck":            "الرقبة",
            "target_body":            "الجسم",
            "err_device_mismatch":    "المفتاح مرتبط بجهاز آخر",
            "err_expired":            "مفتاح الترخيص منتهي",
        ]

        // ──────────────────────────────────────── STANDARD ARABIC ────────────
        case .arabic: return [
            "select_language":        "اختر اللغة",
            "continue":               "متابعة",
            "login_title":            "FF External",
            "login_subtitle":         "أدخل مفتاح الترخيص للمتابعة",
            "key_placeholder":        "FFEX-XXXX-XXXX-XXXX",
            "validate":               "تحقق",
            "validating":             "جارٍ التحقق…",
            "key_invalid":            "المفتاح غير صالح أو منتهي الصلاحية",
            "key_valid":              "تم منح الوصول",
            "logout":                 "تسجيل الخروج",
            "logout_confirm_title":   "تسجيل الخروج",
            "logout_confirm_msg":     "ستحتاج إلى إدخال مفتاحك مرة أخرى.",
            "logout_confirm_yes":     "خروج",
            "logout_confirm_cancel":  "إلغاء",
            "device":                 "الجهاز",
            "expires":                "تنتهي الصلاحية",
            "key_label":              "مفتاح الترخيص",
            "card_iphone":            "آيفون",
            "card_ios":               "iOS",
            "card_expires":           "الوقت المتبقي",
            "tab_ff":                 "فري فاير",
            "tab_ffmax":              "FF Max",
            "inject":                 "حقن الغش",
            "restore":                "استعادة الافتراضي",
            "injecting":              "جارٍ الحقن…",
            "inject_success":         "نجح الحقن",
            "restore_success":        "تم استعادة الملفات",
            "already_injected":       "تم الحقن مسبقاً",
            "unavailable":            "غير متوفر",
            "loading_files":          "جارٍ جلب ملفات الغش…",
            "telegram":               "انضم إلى تيليغرام للتحديثات",
            "section_aiming":         "التصويب",
            "section_movement":       "الحركة",
            "section_combat":         "القتال",
            "section_esp":            "ESP",
            "section_hud":            "HUD",
            "section_stealth":        "التخفي",
            "feat_aimsilent":         "AimSilent",
            "feat_aimsilent_sub":     "تتبع الرصاص للعدو بصمت",
            "feat_aimbot":            "Aimbot",
            "feat_aimbot_sub":        "التصويب التلقائي على الهدف",
            "feat_fov":               "دائرة FOV",
            "feat_fov_sub":           "مؤشر نطاق التصويب",
            "feat_speed":             "Speed Hack",
            "feat_speed_sub":         "سرعة حركة مضاعفة ×5",
            "feat_bulletspeed":       "سرعة الرصاص",
            "feat_bulletspeed_sub":   "معدل إطلاق سريع",
            "feat_fps":               "فتح FPS",
            "feat_fps_sub":           "144 إطار في الثانية",
            "feat_esp_box":           "Box ESP",
            "feat_esp_box_sub":       "مربع تحديد الأعداء",
            "feat_esp_line":          "Line ESP",
            "feat_esp_line_sub":      "خط من حافة الشاشة إلى العدو",
            "feat_esp_health":        "شريط الصحة",
            "feat_esp_health_sub":    "عرض صحة الأعداء",
            "feat_esp_name":          "اسم العدو",
            "feat_esp_name_sub":      "عرض اسم العدو",
            "feat_esp_distance":      "علامة المسافة",
            "feat_esp_distance_sub":  "المسافة بالأمتار",
            "feat_esp_skeleton":      "Skeleton ESP",
            "feat_esp_skeleton_sub":  "طبقة الهيكل العظمي",
            "feat_counter":           "عداد الأعداء",
            "feat_counter_sub":       "العدد الحي في أعلى الشاشة",
            "feat_streamproof":       "Streamproof",
            "feat_streamproof_sub":   "إخفاء ESP من التسجيلات",
            "slider_fov_radius":      "نطاق الرؤية",
            "slider_strength":        "القوة",
            "slider_distance":        "أقصى مسافة",
            "lbl_metres":             "م",
            "target_head":            "الرأس",
            "target_neck":            "الرقبة",
            "target_body":            "الجسم",
            "err_device_mismatch":    "المفتاح مرتبط بجهاز آخر",
            "err_expired":            "انتهت صلاحية مفتاح الترخيص",
        ]

        // ──────────────────────────────────────── TAIWANESE ──────────────────
        case .taiwanese: return [
            "select_language":        "選擇語言",
            "continue":               "繼續",
            "login_title":            "FF External",
            "login_subtitle":         "輸入您的授權金鑰以繼續",
            "key_placeholder":        "FFEX-XXXX-XXXX-XXXX",
            "validate":               "驗證",
            "validating":             "驗證中…",
            "key_invalid":            "金鑰無效或已過期",
            "key_valid":              "已授予訪問權限",
            "logout":                 "登出",
            "logout_confirm_title":   "登出",
            "logout_confirm_msg":     "您需要重新輸入金鑰。",
            "logout_confirm_yes":     "登出",
            "logout_confirm_cancel":  "取消",
            "device":                 "裝置",
            "expires":                "到期",
            "key_label":              "授權金鑰",
            "card_iphone":            "iPhone",
            "card_ios":               "iOS",
            "card_expires":           "剩餘時間",
            "tab_ff":                 "Free Fire",
            "tab_ffmax":              "FF Max",
            "inject":                 "注入外掛",
            "restore":                "還原預設",
            "injecting":              "注入中…",
            "inject_success":         "注入成功",
            "restore_success":        "檔案已還原",
            "already_injected":       "已注入",
            "unavailable":            "不可用",
            "loading_files":          "正在獲取外掛檔案…",
            "telegram":               "加入 Telegram 獲取更新",
            "section_aiming":         "瞄準",
            "section_movement":       "移動",
            "section_combat":         "戰鬥",
            "section_esp":            "ESP",
            "section_hud":            "HUD",
            "section_stealth":        "隱身",
            "feat_aimsilent":         "AimSilent",
            "feat_aimsilent_sub":     "子彈靜默追蹤敵人",
            "feat_aimbot":            "Aimbot",
            "feat_aimbot_sub":        "自動瞄準目標",
            "feat_fov":               "FOV 圓圈",
            "feat_fov_sub":           "瞄準半徑指示器",
            "feat_speed":             "Speed Hack",
            "feat_speed_sub":         "移動速度 5×",
            "feat_bulletspeed":       "子彈速度",
            "feat_bulletspeed_sub":   "快速射速",
            "feat_fps":               "解鎖 FPS",
            "feat_fps_sub":           "144 FPS",
            "feat_esp_box":           "Box ESP",
            "feat_esp_box_sub":       "敵人包圍框",
            "feat_esp_line":          "Line ESP",
            "feat_esp_line_sub":      "螢幕邊緣到敵人的連線",
            "feat_esp_health":        "血量條",
            "feat_esp_health_sub":    "顯示敵人血量",
            "feat_esp_name":          "名稱標籤",
            "feat_esp_name_sub":      "顯示敵人名稱",
            "feat_esp_distance":      "距離標籤",
            "feat_esp_distance_sub":  "以公尺顯示距離",
            "feat_esp_skeleton":      "骨骼 ESP",
            "feat_esp_skeleton_sub":  "骨骼線條疊加",
            "feat_counter":           "敵人計數器",
            "feat_counter_sub":       "螢幕頂部顯示敵人數量",
            "feat_streamproof":       "Streamproof",
            "feat_streamproof_sub":   "錄製時隱藏 ESP",
            "slider_fov_radius":      "半徑",
            "slider_strength":        "強度",
            "slider_distance":        "最大距離",
            "lbl_metres":             "公尺",
            "target_head":            "頭部",
            "target_neck":            "頸部",
            "target_body":            "身體",
            "err_device_mismatch":    "金鑰已綁定至其他裝置",
            "err_expired":            "授權金鑰已過期",
        ]
        }
    }
}

// MARK: - Environment Key

private struct FFLanguageKey: EnvironmentKey {
    static let defaultValue = FFLanguage.english
}

extension EnvironmentValues {
    var ffLanguage: FFLanguage {
        get { self[FFLanguageKey.self] }
        set { self[FFLanguageKey.self] = newValue }
    }
}
